### PR TITLE
Update test runner to Vim 9.0

### PR DESCRIPTION
**Pull request by BNAndras**
Once merged, this will allow us to target Vim 9.0. Switching base images and running vanilla vim instead of vim-gtk results in an 100MB image, down from 150 MB. That can be further cut down to 50 MB since I'm not sure we need Python for the test runner either.

 If this looks good, I'll update the golden tests. The test output looks similar except for some Unicode encoding characters (guessing escape characters) are shifted around in the failure cases. The content itself looks right.

At that point, I can mark this PR ready for Erik's review.

### CODE REVIEW

**Comment by BNAndras** [comment]
This PR can also be where we handle Vim9script or we can do a follow-up PR for that.

**Comment by kotp** [comment]
> The test output looks similar except for some Unicode encoding characters (guessing escape characters) are shifted around in the failure cases.

Those are "terminal control characters" and result from capturing, often, ANSI characters from the terminal.  To get away from those you can sometimes toggle a "colors" option, or some other option that indicates that you want plain text.  I do not know if there is such an option for the tooling being used, but that is a start point to store "cleaner" captures.

**Review by kotp — APPROVED** [review]

**Comment by BNAndras** [comment]
Thanks, I’ll take a look.

**Review by ErikSchierboom — APPROVED** [review]
LGTM!

**Pull request merged**
